# coding: utf-8

"""
    OmicIDX

        The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swatterdoc) - [ReDoc (more readable in some ways)](/redoc)    # noqa: E501

    The version of the OpenAPI document: 0.99
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.sra_api import SRAApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSRAApi(unittest.TestCase):
    """SRAApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.sra_api.SRAApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_experiment_by_accession_sra_experiments_accession_get(self):
        """Test case for experiment_by_accession_sra_experiments_accession_get

        Experiment By Accession  # noqa: E501
        """
        pass

    def test_experiment_by_accession_sra_experiments_accession_get_0(self):
        """Test case for experiment_by_accession_sra_experiments_accession_get_0

        Experiment By Accession  # noqa: E501
        """
        pass

    def test_experiments_for_sample_sra_samples_accession_experiments_get(self):
        """Test case for experiments_for_sample_sra_samples_accession_experiments_get

        Experiments For Sample  # noqa: E501
        """
        pass

    def test_experiments_for_sample_sra_samples_accession_experiments_get_0(self):
        """Test case for experiments_for_sample_sra_samples_accession_experiments_get_0

        Experiments For Sample  # noqa: E501
        """
        pass

    def test_experiments_for_study_sra_studies_accession_experiments_get(self):
        """Test case for experiments_for_study_sra_studies_accession_experiments_get

        Experiments For Study  # noqa: E501
        """
        pass

    def test_experiments_for_study_sra_studies_accession_experiments_get_0(self):
        """Test case for experiments_for_study_sra_studies_accession_experiments_get_0

        Experiments For Study  # noqa: E501
        """
        pass

    def test_experiments_sra_experiments_get(self):
        """Test case for experiments_sra_experiments_get

        Experiments  # noqa: E501
        """
        pass

    def test_experiments_sra_experiments_get_0(self):
        """Test case for experiments_sra_experiments_get_0

        Experiments  # noqa: E501
        """
        pass

    def test_mapping_sra_fields_entity_get(self):
        """Test case for mapping_sra_fields_entity_get

        Mapping  # noqa: E501
        """
        pass

    def test_run_by_accession_sra_runs_accession_get(self):
        """Test case for run_by_accession_sra_runs_accession_get

        Run By Accession  # noqa: E501
        """
        pass

    def test_run_by_accession_sra_runs_accession_get_0(self):
        """Test case for run_by_accession_sra_runs_accession_get_0

        Run By Accession  # noqa: E501
        """
        pass

    def test_runs_for_experiment_sra_experiments_accession_runs_get(self):
        """Test case for runs_for_experiment_sra_experiments_accession_runs_get

        Runs For Experiment  # noqa: E501
        """
        pass

    def test_runs_for_experiment_sra_experiments_accession_runs_get_0(self):
        """Test case for runs_for_experiment_sra_experiments_accession_runs_get_0

        Runs For Experiment  # noqa: E501
        """
        pass

    def test_runs_for_sample_sra_samples_accession_runs_get(self):
        """Test case for runs_for_sample_sra_samples_accession_runs_get

        Runs For Sample  # noqa: E501
        """
        pass

    def test_runs_for_sample_sra_samples_accession_runs_get_0(self):
        """Test case for runs_for_sample_sra_samples_accession_runs_get_0

        Runs For Sample  # noqa: E501
        """
        pass

    def test_runs_for_study_sra_studies_accession_runs_get(self):
        """Test case for runs_for_study_sra_studies_accession_runs_get

        Runs For Study  # noqa: E501
        """
        pass

    def test_runs_for_study_sra_studies_accession_runs_get_0(self):
        """Test case for runs_for_study_sra_studies_accession_runs_get_0

        Runs For Study  # noqa: E501
        """
        pass

    def test_runs_sra_runs_get(self):
        """Test case for runs_sra_runs_get

        Runs  # noqa: E501
        """
        pass

    def test_runs_sra_runs_get_0(self):
        """Test case for runs_sra_runs_get_0

        Runs  # noqa: E501
        """
        pass

    def test_sample_by_accession_sra_samples_accession_get(self):
        """Test case for sample_by_accession_sra_samples_accession_get

        Sample By Accession  # noqa: E501
        """
        pass

    def test_sample_by_accession_sra_samples_accession_get_0(self):
        """Test case for sample_by_accession_sra_samples_accession_get_0

        Sample By Accession  # noqa: E501
        """
        pass

    def test_samples_for_study_sra_studies_accession_samples_get(self):
        """Test case for samples_for_study_sra_studies_accession_samples_get

        Samples For Study  # noqa: E501
        """
        pass

    def test_samples_for_study_sra_studies_accession_samples_get_0(self):
        """Test case for samples_for_study_sra_studies_accession_samples_get_0

        Samples For Study  # noqa: E501
        """
        pass

    def test_samples_sra_samples_get(self):
        """Test case for samples_sra_samples_get

        Samples  # noqa: E501
        """
        pass

    def test_samples_sra_samples_get_0(self):
        """Test case for samples_sra_samples_get_0

        Samples  # noqa: E501
        """
        pass

    def test_studies_sra_studies_get(self):
        """Test case for studies_sra_studies_get

        Studies  # noqa: E501
        """
        pass

    def test_studies_sra_studies_get_0(self):
        """Test case for studies_sra_studies_get_0

        Studies  # noqa: E501
        """
        pass

    def test_study_by_accession_sra_studies_accession_get(self):
        """Test case for study_by_accession_sra_studies_accession_get

        Study By Accession  # noqa: E501
        """
        pass

    def test_study_by_accession_sra_studies_accession_get_0(self):
        """Test case for study_by_accession_sra_studies_accession_get_0

        Study By Accession  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
