# coding: utf-8

"""
    OmicIDX

        The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swatterdoc) - [ReDoc (more readable in some ways)](/redoc)    # noqa: E501

    The version of the OpenAPI document: 0.99
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.geo_api import GEOApi  # noqa: E501
from openapi_client.rest import ApiException


class TestGEOApi(unittest.TestCase):
    """GEOApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.geo_api.GEOApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mapping_geo_fields_entity_get(self):
        """Test case for mapping_geo_fields_entity_get

        Mapping  # noqa: E501
        """
        pass

    def test_platform_by_accession_geo_platform_accession_get(self):
        """Test case for platform_by_accession_geo_platform_accession_get

        Platform By Accession  # noqa: E501
        """
        pass

    def test_platform_by_accession_geo_platform_accession_get_0(self):
        """Test case for platform_by_accession_geo_platform_accession_get_0

        Platform By Accession  # noqa: E501
        """
        pass

    def test_platform_geo_platforms_get(self):
        """Test case for platform_geo_platforms_get

        Platform  # noqa: E501
        """
        pass

    def test_platform_geo_platforms_get_0(self):
        """Test case for platform_geo_platforms_get_0

        Platform  # noqa: E501
        """
        pass

    def test_sample_by_accession_geo_samples_accession_get(self):
        """Test case for sample_by_accession_geo_samples_accession_get

        Sample By Accession  # noqa: E501
        """
        pass

    def test_sample_by_accession_geo_samples_accession_get_0(self):
        """Test case for sample_by_accession_geo_samples_accession_get_0

        Sample By Accession  # noqa: E501
        """
        pass

    def test_samples_for_platform_geo_platforms_accession_samples_get(self):
        """Test case for samples_for_platform_geo_platforms_accession_samples_get

        Samples For Platform  # noqa: E501
        """
        pass

    def test_samples_for_platform_geo_platforms_accession_samples_get_0(self):
        """Test case for samples_for_platform_geo_platforms_accession_samples_get_0

        Samples For Platform  # noqa: E501
        """
        pass

    def test_samples_geo_samples_get(self):
        """Test case for samples_geo_samples_get

        Samples  # noqa: E501
        """
        pass

    def test_samples_geo_samples_get_0(self):
        """Test case for samples_geo_samples_get_0

        Samples  # noqa: E501
        """
        pass

    def test_series_by_accession_geo_series_accession_get(self):
        """Test case for series_by_accession_geo_series_accession_get

        Series By Accession  # noqa: E501
        """
        pass

    def test_series_by_accession_geo_series_accession_get_0(self):
        """Test case for series_by_accession_geo_series_accession_get_0

        Series By Accession  # noqa: E501
        """
        pass

    def test_series_geo_series_get(self):
        """Test case for series_geo_series_get

        Series  # noqa: E501
        """
        pass

    def test_series_geo_series_get_0(self):
        """Test case for series_geo_series_get_0

        Series  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
