# coding: utf-8

"""
    OmicIDX

        The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swatterdoc) - [ReDoc (more readable in some ways)](/redoc)    # noqa: E501

    The version of the OpenAPI document: 0.99
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.biosample_api import BiosampleApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBiosampleApi(unittest.TestCase):
    """BiosampleApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.biosample_api.BiosampleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_biosample_by_accession_biosample_samples_accession_get(self):
        """Test case for biosample_by_accession_biosample_samples_accession_get

        Biosample By Accession  # noqa: E501
        """
        pass

    def test_biosample_by_accession_biosample_samples_accession_get_0(self):
        """Test case for biosample_by_accession_biosample_samples_accession_get_0

        Biosample By Accession  # noqa: E501
        """
        pass

    def test_biosamples_biosample_samples_get(self):
        """Test case for biosamples_biosample_samples_get

        Biosamples  # noqa: E501
        """
        pass

    def test_biosamples_biosample_samples_get_0(self):
        """Test case for biosamples_biosample_samples_get_0

        Biosamples  # noqa: E501
        """
        pass

    def test_mapping_biosample_fields_entity_get(self):
        """Test case for mapping_biosample_fields_entity_get

        Mapping  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
