/*
 * OmicIDX
 *
 *     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swatterdoc) - [ReDoc (more readable in some ways)](/redoc)  
 *
 * API version: 0.99
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package omicidx_client
// ResponseModel struct for ResponseModel
type ResponseModel struct {
	Hits []map[string]interface{} `json:"hits"`
	Facets []map[string]interface{} `json:"facets"`
	Stats ResponseStats `json:"stats"`
	Success bool `json:"success"`
	Cursor string `json:"cursor,omitempty"`
}
