/*
 * OmicIDX
 *
 *     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swatterdoc) - [ReDoc (more readable in some ways)](/redoc)  
 *
 * API version: 0.99
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ValidationError struct for ValidationError
type ValidationError struct {
	Loc []string `json:"loc"`
	Msg string `json:"msg"`
	Type string `json:"type"`
}
