# coding: utf-8

"""
    OmicIDX

        The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swaggerdoc) - [ReDoc (more readable in some ways)](/redoc)    # noqa: E501

    The version of the OpenAPI document: 0.99
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import omicidx_client
from omicidx_client.api.geo_platforms_api import GEOPlatformsApi  # noqa: E501
from omicidx_client.rest import ApiException


class TestGEOPlatformsApi(unittest.TestCase):
    """GEOPlatformsApi unit test stubs"""

    def setUp(self):
        self.api = omicidx_client.api.geo_platforms_api.GEOPlatformsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_by_accession_geo_platform_accession_get(self):
        """Test case for by_accession_geo_platform_accession_get

        Platform By Accession  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
